import chokidar, { watch } from "chokidar";
import consola from "consola";
import { getConfig } from "../config/get-config";
import { restart } from "./restart";

/**
 * File to watch for changes in the required directories. Please do not edit this file.
 */
export const watcher = async () => {
	const config = await getConfig();
	const watcher = chokidar.watch(".", {
		persistent: true,
		ignoreInitial: true,
		ignored: (path: string, stats?: import("fs").Stats): boolean => {
			if (stats?.isDirectory()) {
				return path.includes("node_modules") || path.includes(config.devDir);
			}
			return false;
		},
	});

	watcher
		.on("add", async (path) => {
			consola.info(`File added: ${path}`);
			await restart();
		})
		.on("change", async (path) => {
			consola.info(`File changed: ${path}`);
			await restart();
		})
		.on("unlink", async (path) => {
			consola.info(`File removed: ${path}`);
			await restart();
		});

	process.on("SIGINT", () => {
		// close watcher when Ctrl-C is pressed
		console.log("\n\n");
		consola.info("Closing watcher...");
		watcher.close();

		process.exit(0);
	});
};
