import { watch } from "node:fs";
import consola from "consola";
import { getConfig } from "../config/get-config";

/**
 * File to watch for changes in the required directories. Please do not edit this file.
 */
export const watcher = async () => {
	const config = await getConfig();

	const rootPath = process.cwd();

	const assetsDir = config.assetsDir;
	const routesDir = config.routesDir;
	const pagesDir = config.pagesDir;

	// listening for changes in the assets directory
	const watcher = watch(`${rootPath}`, (event, filename) => {
		console.log(`Detected ${event} in ${filename}`);
	});

	process.on("SIGINT", () => {
		// close watcher when Ctrl-C is pressed
		console.log("\n\n");
		consola.info("Closing watcher...");
		watcher.close();

		process.exit(0);
	});
};
