name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        bun-version: [1.2.15, latest]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: ${{ matrix.bun-version }}
        
    - name: Install dependencies
      run: bun install
      
    - name: Run linting
      run: bun run lint
      continue-on-error: true
      
    - name: Type checking
      run: bun run check-types
      continue-on-error: true
      
    - name: Run CLI tests
      run: |
        cd packages/brosel
        bun test tests/cli.test.ts
        
    - name: Run all tests
      run: |
        cd packages/brosel
        bun test
        
    - name: Test CLI functionality
      run: |
        cd packages/brosel
        # Test help command
        timeout 10s bun run src/cli/index.ts --help || true
        # Test development command (should fail due to missing port but validates parsing)
        timeout 10s bun run src/cli/index.ts dev 2>&1 | grep -q "Required option --port is missing" || echo "CLI error handling working"

  test-windows:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Run CLI tests
      run: |
        cd packages/brosel
        bun test tests/cli.test.ts

  test-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        
    - name: Install dependencies
      run: bun install
      
    - name: Run CLI tests
      run: |
        cd packages/brosel
        bun test tests/cli.test.ts
